name: Processar Dados

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  email: ${{ vars.EMAIL_VAR }}
  nome: ${{ vars.NOME }}

jobs:
  processar:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixar o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 2: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Passo 3: Instalar dependências (ex: pandas)
      - name: Instalar dependências
        run: pip install pandas

      # Passo 4: Executar o script Python
      - name: Executar script
        run: python dados/script.py

      # Passo 5 (Opcional): Verificar se o arquivo foi gerado
      - name: Verificar saída
        run: |
          ls -la resultados/
          cat resultados/saida.csv
      - name: Commit do arquivo gerado
        run: |
          git config --global user.email $email
          git config --global user.name $nome
          git add resultados/saida.csv
          git commit -m "Atualiza arquivo de saída"
          git push